// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PNC.Data;

#nullable disable

namespace PNC.Migrations
{
    [DbContext(typeof(BdPolicePncContext))]
    [Migration("20250903171820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PNC.Models.Audit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("AdresseIP")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("adresseIP");

                    b.Property<string>("AnciennesValeurs")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("anciennesValeurs");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("datetime")
                        .HasColumnName("dateAction");

                    b.Property<string>("IdEntite")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idEntite");

                    b.Property<string>("IdUtilisateur")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idUtilisateur");

                    b.Property<string>("NouvellesValeurs")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("nouvellesValeurs");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("table");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("userAgent");

                    b.HasKey("Id")
                        .HasName("Audit_PK");

                    b.HasIndex("IdUtilisateur");

                    b.ToTable("Audit", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Commissariat", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("District")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("district");

                    b.Property<string>("Nom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nom");

                    b.Property<string>("Province")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("province");

                    b.Property<string>("Territoire")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("territoire");

                    b.HasKey("Id")
                        .HasName("Commissariat_PK");

                    b.ToTable("Commissariat", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Conjoint", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DateMariage")
                        .HasColumnType("datetime")
                        .HasColumnName("dateMariage");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Matricule")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("matricule");

                    b.Property<string>("Nationalite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nationalite");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nom");

                    b.Property<string>("PostNom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("postNom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("prenom");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("profession");

                    b.HasKey("Id")
                        .HasName("Conjoint_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("Conjoint", (string)null);
                });

            modelBuilder.Entity("PNC.Models.DistinctionHonorifique", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateDecision")
                        .HasColumnType("datetime")
                        .HasColumnName("dateDecision");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("motif");

                    b.Property<string>("NumeroDecision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numeroDecision");

                    b.HasKey("Id")
                        .HasName("DistinctionHonorifique_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("DistinctionHonorifique", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreation");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("datetime")
                        .HasColumnName("dateModification");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit")
                        .HasColumnName("estActif");

                    b.Property<string>("Extension")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("extension");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<long?>("TailleFichier")
                        .HasColumnType("bigint")
                        .HasColumnName("tailleFichier");

                    b.Property<string>("TypeDocument")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("typeDocument");

                    b.Property<string>("UrlDocument")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("urlDocument");

                    b.HasKey("Id")
                        .HasName("Document_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Empreinte", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("id");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("TypeDoigt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("typeDoigt");

                    b.Property<string>("Urlepreinte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Empreint__3213E83FA6E4BA03");

                    b.HasIndex("IdPolicier");

                    b.ToTable("Empreinte", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Enfant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime")
                        .HasColumnName("dateNaissance");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nom");

                    b.Property<string>("PaysNaissance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("paysNaissance");

                    b.Property<string>("PostNom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("postNom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("prenom");

                    b.Property<string>("VilleNaissance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("villeNaissance");

                    b.HasKey("Id")
                        .HasName("Enfant_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("Enfant", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Enqueteur", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("Adresse")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("adresse");

                    b.Property<string>("CodeIdentification")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codeIdentification");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nom");

                    b.Property<string>("PostNom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("postNom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("Enqueteur_PK");

                    b.ToTable("Enqueteur", (string)null);
                });

            modelBuilder.Entity("PNC.Models.FonctionBefore1997", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("ActeNomination")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("acteNomination");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("datetime")
                        .HasColumnName("dateEntree");

                    b.Property<string>("DernierGrade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dernierGrade");

                    b.Property<string>("IdCommissariat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idCommissariat");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("lieu");

                    b.Property<string>("MatriculeOrigine")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("matriculeOrigine");

                    b.Property<string>("Ministere")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ministere");

                    b.Property<string>("NatureGrade")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("natureGrade");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("service");

                    b.HasKey("Id")
                        .HasName("FonctionBefore1997_PK");

                    b.HasIndex("IdCommissariat");

                    b.ToTable("FonctionBefore1997", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Formation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<int>("Annee")
                        .HasColumnType("int")
                        .HasColumnName("annee");

                    b.Property<string>("Diplome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("diplome");

                    b.Property<string>("Duree")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("duree");

                    b.Property<string>("Ecole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ecole");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nature");

                    b.Property<string>("NomDiplome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nomDiplome");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("pays");

                    b.Property<string>("TypeFormation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("typeFormation");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ville");

                    b.HasKey("Id")
                        .HasName("Formation_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("Formation", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Fri", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<int>("Annee")
                        .HasColumnType("int")
                        .HasColumnName("annee");

                    b.Property<DateTime>("DateRemplissage")
                        .HasColumnType("datetime")
                        .HasColumnName("dateRemplissage");

                    b.Property<string>("IdCommissariat")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idCommissariat");

                    b.Property<string>("IdEnqueteur")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idEnqueteur");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<int>("Jour")
                        .HasColumnType("int")
                        .HasColumnName("jour");

                    b.Property<string>("Mois")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mois");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("FRI_PK");

                    b.HasIndex("IdCommissariat");

                    b.HasIndex("IdEnqueteur");

                    b.HasIndex("IdPolicier");

                    b.ToTable("FRI", (string)null);
                });

            modelBuilder.Entity("PNC.Models.HistAffectation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("ActeDenomination")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("acteDenomination");

                    b.Property<DateTime>("DateActe")
                        .HasColumnType("datetime")
                        .HasColumnName("dateActe");

                    b.Property<string>("Denomination")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("denomination");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("lieu");

                    b.HasKey("Id")
                        .HasName("HistAffectation_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("HistAffectation", (string)null);
                });

            modelBuilder.Entity("PNC.Models.HistFonction", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime")
                        .HasColumnName("dateFin");

                    b.Property<DateTime>("DatePriseFonction")
                        .HasColumnType("datetime")
                        .HasColumnName("datePriseFonction");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("IntituleFonction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("intituleFonction");

                    b.HasKey("Id")
                        .HasName("HistFonction_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("HistFonction", (string)null);
                });

            modelBuilder.Entity("PNC.Models.HistGrade", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("ActeNomination")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("acteNomination");

                    b.Property<DateTime>("DateActe")
                        .HasColumnType("datetime")
                        .HasColumnName("dateActe");

                    b.Property<DateTime>("DateNomination")
                        .HasColumnType("datetime")
                        .HasColumnName("dateNomination");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("intitule");

                    b.HasKey("Id")
                        .HasName("HistGrade_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("HistGrade", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Langue", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("libelle");

                    b.Property<int>("NiveauEcriture")
                        .HasColumnType("int")
                        .HasColumnName("niveauEcriture");

                    b.Property<int>("NiveauLecture")
                        .HasColumnType("int")
                        .HasColumnName("niveauLecture");

                    b.HasKey("Id")
                        .HasName("Langue_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("Langue", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Nutp", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("NumeroNutp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numeroNUTP");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("NUTP", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreation");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit")
                        .HasColumnName("estActif");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("module");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom");

                    b.HasKey("Id")
                        .HasName("Permission_PK");

                    b.HasIndex("Module", "Action")
                        .IsUnique()
                        .HasDatabaseName("IX_Permission_Module_Action");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("PNC.Models.PersonnePrevenir", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("commune");

                    b.Property<string>("IdPolicier")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nom");

                    b.Property<string>("NumeroRue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numeroRue");

                    b.Property<string>("PostNom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("postNom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("prenom");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rue");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("PersonnePrevenir_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("PersonnePrevenir", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Policier", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("ActeNominationFonction")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("acteNominationFonction");

                    b.Property<string>("ActeNominationGrade")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("acteNominationGrade");

                    b.Property<int>("Annee")
                        .HasColumnType("int")
                        .HasColumnName("annee");

                    b.Property<string>("BuCielCiatEscDet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bu_ciel_ciat_esc_det");

                    b.Property<string>("CategoriePermis")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("categoriePermis");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("commune");

                    b.Property<DateTime?>("DateActe")
                        .HasColumnType("datetime")
                        .HasColumnName("dateActe");

                    b.Property<DateTime?>("DateDelivrancePermis")
                        .HasColumnType("datetime")
                        .HasColumnName("dateDelivrancePermis");

                    b.Property<DateTime>("DateEntreePolice")
                        .HasColumnType("datetime")
                        .HasColumnName("dateEntreePolice");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime")
                        .HasColumnName("dateNaissance");

                    b.Property<DateTime?>("DateNomination")
                        .HasColumnType("datetime")
                        .HasColumnName("dateNomination");

                    b.Property<DateTime?>("DatePriseFonction")
                        .HasColumnType("datetime")
                        .HasColumnName("datePriseFonction");

                    b.Property<string>("DeptBnDistGpt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dept_bn_dist_gpt");

                    b.Property<string>("DistrictOrigine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("districtOrigine");

                    b.Property<string>("EtatCivil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("etatCivil");

                    b.Property<string>("FonctionActuelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("fonctionActuelle");

                    b.Property<string>("GroupeSanguin")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("groupeSanguin");

                    b.Property<string>("IdCommissariat")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idCommissariat");

                    b.Property<string>("Jour")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("jour");

                    b.Property<string>("LieuAffectation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("lieuAffectation");

                    b.Property<string>("LieuEntreePolice")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("lieuEntreePolice");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("matricule");

                    b.Property<string>("Mois")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("mois");

                    b.Property<string>("NatureGrade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("natureGrade");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nom");

                    b.Property<string>("NomUnite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nomUnite");

                    b.Property<string>("NumeroNutp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numeroNUTP");

                    b.Property<string>("NumeroPermis")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numeroPermis");

                    b.Property<string>("NumeroRue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("numeroRue");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("observation");

                    b.Property<string>("PaysNaissance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("paysNaissance");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("photo");

                    b.Property<string>("PostNom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("postNom");

                    b.Property<string>("Prenom")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("prenom");

                    b.Property<string>("ProvinceOrigine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("provinceOrigine");

                    b.Property<string>("Rhesus")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("rhesus");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rue");

                    b.Property<string>("SecPiSciatSousDet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sec_pi_sciat_sousDet");

                    b.Property<string>("SecteurOrigine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("secteurOrigine");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sexe");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("signature");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telephone");

                    b.Property<string>("TerritoireOrigine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("territoireOrigine");

                    b.Property<string>("UniteAffectation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("uniteAffectation");

                    b.Property<string>("UniteMere")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("uniteMere");

                    b.Property<string>("VillageNaissance")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("villageNaissance");

                    b.Property<string>("VillageOrigine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("villageOrigine");

                    b.Property<string>("VilleNaissance")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("villeNaissance");

                    b.HasKey("Id")
                        .HasName("Policier_PK");

                    b.HasIndex("IdCommissariat");

                    b.ToTable("Policier", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreation");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit")
                        .HasColumnName("estActif");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom");

                    b.Property<string>("PermissionId")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("Role_PK");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("IX_Role_Nom");

                    b.HasIndex("PermissionId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("PNC.Models.RolePermission", b =>
                {
                    b.Property<string>("IdRole")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idRole");

                    b.Property<string>("IdPermission")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPermission");

                    b.Property<string>("AttribuePar")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("attribuePar");

                    b.Property<DateTime>("DateAttribution")
                        .HasColumnType("datetime")
                        .HasColumnName("dateAttribution");

                    b.HasKey("IdRole", "IdPermission")
                        .HasName("RolePermission_PK");

                    b.HasIndex("IdPermission");

                    b.ToTable("RolePermission", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Sport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<string>("IdPolicier")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idPolicier");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("libelle");

                    b.HasKey("Id")
                        .HasName("Sport_PK");

                    b.HasIndex("IdPolicier");

                    b.ToTable("Sport", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Utilisateur", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime")
                        .HasColumnName("dateCreation");

                    b.Property<DateTime?>("DerniereConnexion")
                        .HasColumnType("datetime")
                        .HasColumnName("derniereConnexion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit")
                        .HasColumnName("estActif");

                    b.Property<string>("IdEnqueteur")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idEnqueteur");

                    b.Property<string>("IdRole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("idRole");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motDePasse");

                    b.Property<bool>("MotDePasseModifie")
                        .HasColumnType("bit")
                        .HasColumnName("motDePasseModifie");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nom");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nomUtilisateur");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("prenom");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telephone");

                    b.HasKey("Id")
                        .HasName("Utilisateur_PK");

                    b.HasIndex("IdEnqueteur");

                    b.HasIndex("IdRole");

                    b.HasIndex("NomUtilisateur")
                        .IsUnique()
                        .HasDatabaseName("IX_Utilisateur_NomUtilisateur");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("PNC.Models.Audit", b =>
                {
                    b.HasOne("PNC.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Audit_Utilisateur");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("PNC.Models.Conjoint", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Conjoints")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_Conjoint");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.DistinctionHonorifique", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("DistinctionHonorifiques")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_DistinctionHonorifique");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.Document", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("IdPolicier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Document_Policier");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.Empreinte", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Empreintes")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK__Empreinte__idPol__5812160E");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.Enfant", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Enfants")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_Enfant");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.FonctionBefore1997", b =>
                {
                    b.HasOne("PNC.Models.Commissariat", "IdCommissariatNavigation")
                        .WithMany("FonctionBefore1997s")
                        .HasForeignKey("IdCommissariat")
                        .IsRequired()
                        .HasConstraintName("FK_Commissariat_FonctionBefore1997");

                    b.Navigation("IdCommissariatNavigation");
                });

            modelBuilder.Entity("PNC.Models.Formation", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Formations")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_Formation");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.Fri", b =>
                {
                    b.HasOne("PNC.Models.Commissariat", "IdCommissariatNavigation")
                        .WithMany("Fris")
                        .HasForeignKey("IdCommissariat")
                        .IsRequired()
                        .HasConstraintName("FK_Commissariat_FRI");

                    b.HasOne("PNC.Models.Enqueteur", "IdEnqueteurNavigation")
                        .WithMany("Fris")
                        .HasForeignKey("IdEnqueteur")
                        .IsRequired()
                        .HasConstraintName("FK_FRI_Enqueteur");

                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Fris")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_FRI");

                    b.Navigation("IdCommissariatNavigation");

                    b.Navigation("IdEnqueteurNavigation");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.HistAffectation", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("HistAffectations")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_HistAffectation");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.HistFonction", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("HistFonctions")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_HistFonction");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.HistGrade", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("HistGrades")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_HistGrade");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.Langue", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Langues")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_Langue");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.PersonnePrevenir", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("PersonnePrevenirs")
                        .HasForeignKey("IdPolicier")
                        .IsRequired()
                        .HasConstraintName("FK_Policier_PersonnePrevenir");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.Policier", b =>
                {
                    b.HasOne("PNC.Models.Commissariat", "IdCommissariatNavigation")
                        .WithMany()
                        .HasForeignKey("IdCommissariat")
                        .HasConstraintName("FK_Policier_Commissariat");

                    b.Navigation("IdCommissariatNavigation");
                });

            modelBuilder.Entity("PNC.Models.Role", b =>
                {
                    b.HasOne("PNC.Models.Permission", null)
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId");
                });

            modelBuilder.Entity("PNC.Models.RolePermission", b =>
                {
                    b.HasOne("PNC.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Permission");

                    b.HasOne("PNC.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RolePermission_Role");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PNC.Models.Sport", b =>
                {
                    b.HasOne("PNC.Models.Policier", "IdPolicierNavigation")
                        .WithMany("Sports")
                        .HasForeignKey("IdPolicier")
                        .HasConstraintName("FK_Policier_Sport");

                    b.Navigation("IdPolicierNavigation");
                });

            modelBuilder.Entity("PNC.Models.Utilisateur", b =>
                {
                    b.HasOne("PNC.Models.Enqueteur", "IdEnqueteurNavigation")
                        .WithMany()
                        .HasForeignKey("IdEnqueteur")
                        .HasConstraintName("FK_Utilisateur_Enqueteur");

                    b.HasOne("PNC.Models.Role", "IdRoleNavigation")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Utilisateur_Role");

                    b.Navigation("IdEnqueteurNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("PNC.Models.Commissariat", b =>
                {
                    b.Navigation("FonctionBefore1997s");

                    b.Navigation("Fris");
                });

            modelBuilder.Entity("PNC.Models.Enqueteur", b =>
                {
                    b.Navigation("Fris");
                });

            modelBuilder.Entity("PNC.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("PNC.Models.Policier", b =>
                {
                    b.Navigation("Conjoints");

                    b.Navigation("DistinctionHonorifiques");

                    b.Navigation("Documents");

                    b.Navigation("Empreintes");

                    b.Navigation("Enfants");

                    b.Navigation("Formations");

                    b.Navigation("Fris");

                    b.Navigation("HistAffectations");

                    b.Navigation("HistFonctions");

                    b.Navigation("HistGrades");

                    b.Navigation("Langues");

                    b.Navigation("PersonnePrevenirs");

                    b.Navigation("Sports");
                });

            modelBuilder.Entity("PNC.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
